/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import entidade.Exemplares;
import javax.swing.JOptionPane;
import percistencia.TudoDaoExemplares;

/**
 *
 * @author jbrag
 */
public class FrameExemplar extends javax.swing.JFrame {

    Exemplares f = new Exemplares();
    TudoDaoExemplares tde = new TudoDaoExemplares();

    public FrameExemplar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblCodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numlocalizacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtBuscar = new javax.swing.JButton();
        BtListar = new javax.swing.JToggleButton();
        BtEditar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopse = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Registro Exemplares");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 210, 55);

        LblCodigo.setText("Código");
        getContentPane().add(LblCodigo);
        LblCodigo.setBounds(77, 107, 45, 31);

        codigo.setEnabled(false);
        getContentPane().add(codigo);
        codigo.setBounds(132, 107, 70, 31);

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(77, 144, 45, 26);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(132, 144, 108, 26);

        jLabel4.setText("Genero");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(77, 183, 45, 14);

        genero.setEnabled(false);
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        getContentPane().add(genero);
        genero.setBounds(132, 176, 108, 28);

        jLabel5.setText("Sinopse");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(316, 107, 55, 14);

        jLabel6.setText("Numero de localização");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(77, 210, 126, 14);

        numlocalizacao.setEnabled(false);
        getContentPane().add(numlocalizacao);
        numlocalizacao.setBounds(77, 230, 126, 30);

        jLabel7.setText("Quantidade");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(213, 210, 124, 14);

        quantidade.setEnabled(false);
        getContentPane().add(quantidade);
        quantidade.setBounds(213, 230, 124, 30);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(518, 25, 80, 23);

        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BtNovo);
        BtNovo.setBounds(50, 310, 70, 23);

        BtSalvar.setText("Salvar");
        BtSalvar.setEnabled(false);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalvar);
        BtSalvar.setBounds(230, 310, 80, 23);

        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtExcluir);
        BtExcluir.setBounds(530, 310, 80, 23);

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtBuscar);
        BtBuscar.setBounds(330, 310, 90, 23);

        BtListar.setText("Listar");
        getContentPane().add(BtListar);
        BtListar.setBounds(440, 310, 70, 23);

        BtEditar.setText("Editar");
        BtEditar.setEnabled(false);
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtEditar);
        BtEditar.setBounds(140, 310, 73, 23);

        cancelar.setText("Cancelar");
        cancelar.setMaximumSize(new java.awt.Dimension(61, 23));
        cancelar.setMinimumSize(new java.awt.Dimension(61, 23));
        cancelar.setPreferredSize(new java.awt.Dimension(61, 23));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(520, 60, 80, 23);

        sinopse.setColumns(20);
        sinopse.setRows(5);
        sinopse.setEnabled(false);
        jScrollPane1.setViewportView(sinopse);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 110, 270, 180);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        MnSair.setText("Sair");

        sair.setText("Sair do sistema");
        MnSair.add(sair);

        jMenuBar1.add(MnSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(679, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        //Campos de texto
        nome.setEnabled(true);
        genero.setEnabled(true);
        numlocalizacao.setEnabled(true);
        sinopse.setEnabled(true);
        quantidade.setEnabled(true);
        //Limpando todos os campos
        nome.setText("");
        genero.setText("");
        numlocalizacao.setText("");
        sinopse.setText("");
        quantidade.setText("");
        //Botões
        BtEditar.setEnabled(false);
        BtSalvar.setEnabled(true);

    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try {
            //inserindo os valores no objeto Exemplares
            f.setNome(nome.getText());
            f.setGenero(genero.getText());
            f.setNumLocalizacao(numlocalizacao.getText());
            f.setSinopse(sinopse.getText());
            f.setQuantidade(Integer.parseInt(quantidade.getText()));
            //Inserindo os dados no banco de dados
            tde.inserir(f);
            //Limpando os campos do formulário
            nome.setText("");
            genero.setText("");
            numlocalizacao.setText("");
            sinopse.setText("");
            quantidade.setText("");
            //Desabilitando os campos do formulário
            genero.setEnabled(false);
            numlocalizacao.setEnabled(false);
            sinopse.setEnabled(false);
            quantidade.setEnabled(false);
            //Botões do formulário
            BtSalvar.setEnabled(false);
            BtBuscar.setEnabled(true);
            BtExcluir.setEnabled(false);

            JOptionPane.showMessageDialog(rootPane, "Dados Inseridos com sucesso!!!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao inserir os dados!!!");
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());

        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            //Criando uma variável para auxiliar na confirmação de exclusão
            int resposta;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja apagar os dados de " + nome.getText());
            if (resposta == JOptionPane.YES_OPTION) {
                //Chamando o método de exclusão e enviando a mensagem de sucesso
                tde.apagarExemplares(Integer.parseInt(codigo.getText()));
                JOptionPane.showMessageDialog(rootPane, "Dados Apagados com sucesso!!!!");
                //Limpando os campos de texto do formulário
                nome.setText("");
                genero.setText("");
                numlocalizacao.setText("");
                sinopse.setText("");
                quantidade.setText("");
                //Habilitando e desabilitando os campos de texto
                nome.setEnabled(true);
                genero.setEditable(false);
                numlocalizacao.setEditable(false);
                sinopse.setEditable(false);
                quantidade.setEditable(false);
                //Habilitando e desabilitando os botões
                BtEditar.setEnabled(false);
                BtExcluir.setEnabled(false);
                BtListar.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar dados!!!");
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        try {
            f = tde.selecionar(nome.getText());
            codigo.setText(String.valueOf(f.getCodigo()));
            nome.setText(f.getNome());
            genero.setText(f.getGenero());
            numlocalizacao.setText(f.getNumLocalizacao());
            sinopse.setText(f.getSinopse());
            quantidade.setText(String.valueOf(f.getQuantidade()));

            BtEditar.setEnabled(true);
            nome.setEnabled(false);
            genero.setEnabled(false);
            numlocalizacao.setEnabled(false);
            sinopse.setEnabled(false);
            quantidade.setEnabled(false);
            BtExcluir.setEnabled(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Buscar os dados!!!");
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        //Botões do formulário
        BtSalvar.setEnabled(true);
        BtListar.setEnabled(false);
        BtBuscar.setEnabled(false);
        //Campo do formulário
        nome.setEnabled(true);
        genero.setEnabled(true);
        numlocalizacao.setEnabled(true);
        sinopse.setEnabled(true);
        quantidade.setEnabled(true);


    }//GEN-LAST:event_BtEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        //Campos de texto
        nome.setText("");
        genero.setText("");
        numlocalizacao.setText("");
        sinopse.setText("");
        quantidade.setText("");
        //Botões
        BtNovo.setEnabled(true);
        BtBuscar.setEnabled(true);
        BtListar.setEnabled(true);
        BtEditar.setEnabled(false);
        BtExcluir.setEnabled(false);
        BtSalvar.setEnabled(false);
        //Campos habilitados
        nome.setEnabled(true);
        genero.setEnabled(false);
        numlocalizacao.setEnabled(false);
        sinopse.setEnabled(false);
        quantidade.setEnabled(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameExemplar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JToggleButton BtListar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JMenu MnSair;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numlocalizacao;
    private javax.swing.JTextField quantidade;
    private javax.swing.JMenuItem sair;
    private javax.swing.JTextArea sinopse;
    // End of variables declaration//GEN-END:variables
}
