/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import entidade.Locacao;
import javax.swing.JOptionPane;
import percistencia.TudoDaoExemplares;
import percistencia.TudoDaoLocacao;

/**
 *
 * @author jbrag
 */
public class FrameLocacao extends javax.swing.JFrame {

    Locacao l = new Locacao();
    TudoDaoLocacao tdl = new TudoDaoLocacao();
    TudoDaoExemplares tde = new TudoDaoExemplares();
    int flag = 1;
    
    public FrameLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtBuscar = new javax.swing.JButton();
        BtListar = new javax.swing.JToggleButton();
        BtEditar = new javax.swing.JButton();
        emprestimo = new javax.swing.JFormattedTextField();
        previsaodevolucao = new javax.swing.JFormattedTextField();
        exemplar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        observacao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        devolucao = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Registro Locação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(222, 11, 184, 36);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(522, 24, 61, 23);

        jLabel2.setText("Exemplar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 70, 80, 14);

        jLabel3.setText("Data do Emprestimo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 134, 180, 14);

        jLabel4.setText("Data Prevista de devolução");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 180, 14);

        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BtNovo);
        BtNovo.setBounds(20, 300, 70, 23);

        BtSalvar.setText("Salvar");
        BtSalvar.setEnabled(false);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalvar);
        BtSalvar.setBounds(200, 300, 80, 23);

        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtExcluir);
        BtExcluir.setBounds(470, 300, 80, 23);

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtBuscar);
        BtBuscar.setBounds(290, 300, 70, 23);

        BtListar.setText("Listar");
        getContentPane().add(BtListar);
        BtListar.setBounds(380, 300, 70, 23);

        BtEditar.setText("Editar");
        BtEditar.setEnabled(false);
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtEditar);
        BtEditar.setBounds(110, 300, 73, 23);

        try {
            emprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        emprestimo.setEnabled(false);
        getContentPane().add(emprestimo);
        emprestimo.setBounds(40, 159, 179, 30);

        try {
            previsaodevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        previsaodevolucao.setEnabled(false);
        getContentPane().add(previsaodevolucao);
        previsaodevolucao.setBounds(40, 215, 179, 30);
        getContentPane().add(exemplar);
        exemplar.setBounds(340, 60, 160, 30);

        jLabel5.setText("Codigo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 74, 52, 23);

        codigo.setEnabled(false);
        getContentPane().add(codigo);
        codigo.setBounds(102, 65, 77, 30);

        jLabel6.setText("Status Empréstimo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(218, 103, 110, 25);

        status.setEnabled(false);
        getContentPane().add(status);
        status.setBounds(345, 105, 160, 30);

        jLabel7.setText("Observações");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 210, 220, 26);

        observacao.setEnabled(false);
        getContentPane().add(observacao);
        observacao.setBounds(230, 230, 232, 30);

        jLabel8.setText("Data da Devolução");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 150, 140, 14);

        try {
            devolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        devolucao.setEnabled(false);
        getContentPane().add(devolucao);
        devolucao.setBounds(230, 180, 280, 30);

        jLabel9.setText("Quantidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 260, 64, 14);

        quantidade.setText("0");
        quantidade.setEnabled(false);
        getContentPane().add(quantidade);
        quantidade.setBounds(114, 253, 105, 30);

        setSize(new java.awt.Dimension(606, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        //Campos de texto
        emprestimo.setEnabled(true);
        previsaodevolucao.setEnabled(true);
        status.setEnabled(true);
        devolucao.setEnabled(true);
        observacao.setEnabled(true);
        quantidade.setEnabled(true);
        //Limpando todos os campos
        codigo.setText("");
        emprestimo.setText("");
        previsaodevolucao.setText("");
        status.setText("");
        devolucao.setText("");
        observacao.setText("");
        quantidade.setText("");
        //Botões
        BtEditar.setEnabled(false);
        BtSalvar.setEnabled(true);
        BtExcluir.setEnabled(false);
        BtBuscar.setEnabled(false);
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try {
            //inserindo os valores no objeto Exemplares
            l.setDataEmprestimo(tdl.dataDB(emprestimo.getText()));
            l.setDataPrevista(tdl.dataDB(previsaodevolucao.getText()));
            l.setDataDevolucao(tdl.dataDB(devolucao.getText()));
            l.setObservacao(observacao.getText());
            l.setStatus(status.getText());
            l.setExemplrar(exemplar.getText());
            //Inserindo os dados no banco de dados
            if(flag == 1){
                System.out.println("Entrou aqui");
                tdl.inserir(l);
                tde.modificar(exemplar.getName(), Integer.parseInt(quantidade.getText()));
            }else{
                tdl.modificar("string");
                tdl.modificar(l.getExemplrar());
            }
            //Limpando os campos do formulário
            quantidade.setText("");
            devolucao.setText("");
            emprestimo.setText("");
            status.setText("");
            observacao.setText("");
            previsaodevolucao.setText("");
            //Desabilitando os campos do formulário
            quantidade.setEnabled(false);
            previsaodevolucao.setEnabled(false);
            devolucao.setEnabled(false);
            emprestimo.setEnabled(false);
            status.setEnabled(false);
            observacao.setEnabled(false);
            //Botões do formulário
            BtSalvar.setEnabled(false);
            BtBuscar.setEnabled(true);
            BtExcluir.setEnabled(false);

            JOptionPane.showMessageDialog(rootPane, "Dados Inseridos com sucesso!!!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao inserir os dados!!!");
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());

        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            //Criando uma variável para auxiliar na confirmação de exclusão
            int resposta;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja apagar os dados de " + exemplar.getText());
            if (resposta == JOptionPane.YES_OPTION) {
                //Chamando o método de exclusão e enviando a mensagem de sucesso
                tdl.apagarLocacao(Integer.parseInt(codigo.getText()));
                JOptionPane.showMessageDialog(rootPane, "Dados Apagados com sucesso!!!!");
                //Limpando os campos de texto do formulário
                observacao.setText("");
                devolucao.setText("");
                previsaodevolucao.setText("");
                emprestimo.setText("");
                status.setText("");
                //Habilitando e desabilitando os campos de texto
                observacao.setEnabled(true);
                devolucao.setEditable(false);
                previsaodevolucao.setEditable(false);
                emprestimo.setEditable(false);
                status.setEditable(false);
                //Habilitando e desabilitando os botões
                BtEditar.setEnabled(false);
                BtExcluir.setEnabled(false);
                BtListar.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao apagar dados!!!");
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        try {
            if (!(exemplar.getText().isEmpty())) {
                l = tdl.selecionar(exemplar.getText());
                codigo.setText(String.valueOf(l.getCodigo()));
                devolucao.setText(l.getDataDevolucao());
                observacao.setText(l.getObservacao());
                status.setText(l.getStatus());
                emprestimo.setText(l.getDataEmprestimo());
                previsaodevolucao.setText(l.getDataPrevista());
                //Campos de texto
                status.setEnabled(false);
                devolucao.setEnabled(false);
                previsaodevolucao.setEnabled(false);
                observacao.setEnabled(false);
                emprestimo.setEnabled(false);
                //Botões
                BtBuscar.setEnabled(false);
                BtEditar.setEnabled(true);
                BtExcluir.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Preencha o campo Exemplar pra realizar a busca!!!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Buscar os dados!!!");
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        //Botões do formulário
        flag = 2;
        BtSalvar.setEnabled(true);
        BtListar.setEnabled(false);
        BtBuscar.setEnabled(false);
        //Campo do formulário
        devolucao.setEnabled(true);
        previsaodevolucao.setEnabled(true);
        status.setEnabled(true);
        observacao.setEnabled(true);
        emprestimo.setEnabled(true);
    }//GEN-LAST:event_BtEditarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
       dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        //Campos de texto
        devolucao.setText("");
        previsaodevolucao.setText("");
        status.setText("");
        observacao.setText("");
        emprestimo.setText("");
        //Botões
        BtNovo.setEnabled(true);
        BtBuscar.setEnabled(true);
        BtListar.setEnabled(true);
        BtEditar.setEnabled(false);
        BtExcluir.setEnabled(false);
        BtSalvar.setEnabled(false);
        //Campos habilitados
        devolucao.setEnabled(true);
        previsaodevolucao.setEnabled(false);
        status.setEnabled(false);
        observacao.setEnabled(false);
        emprestimo.setEnabled(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JToggleButton BtListar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JFormattedTextField devolucao;
    private javax.swing.JFormattedTextField emprestimo;
    private javax.swing.JTextField exemplar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField observacao;
    private javax.swing.JFormattedTextField previsaodevolucao;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField status;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
